openapi: 3.0.0
info:
  title: 법령 검색 API
  version: 1.0.0
servers:
  - url: https://your-render-service.onrender.com  # 추후 실제 URL로 교체
paths:
  /search:
    get:
      summary: 키워드로 법령 검색
      description: 키워드를 통해 국가법령정보센터 API를 호출하여 관련 법령을 반환합니다.
      parameters:
        - in: query
          name: keyword
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 검색 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  results:
                    type: array
                    items:
                      type: string
